default:
  github:
    baseUrl: 'https://api.github.com/repos/VentasPrivadas/'
    email: 'mail@dominio.com'
    pass: 'password'
  asana:
    apiKey: 'APIKEY'
    projectId: PROYECT_ID
  aws:
    key: ''
    secret: ''
    region: 'us-west-2'
  mongodb:
      server: 'mongodb://domain:port'
      dbName: 'collectionName'
dev:
staging:
production:

